### ISSUE TITLE
Migrate to object oriented php

### ISSUE THREAD

**Issue by alexandermarston** [alexandermarston/vnstat-dashboard#20]
The code base should be migrated to an object oriented style of code.

**Comment by JellyBellyDev** [comment]
Hello!
Can I try it?

**Comment by dangenendt** [comment]
I can do that. 
Anything against using a template engine like Twig/Blade/Smarty for the html stuff? 
Using one of them would bring the "need" for composer (con because of a little more complexity of the application)... but with composer and the change to an object-oriented style you don't need to worry about autoloading then (pro) ;).

**Comment by alexandermarston** [comment]
Sounds good to me, @dangenendt 

Nothing against using a template engine - happy with the need for composer.

**Comment by dangenendt** [comment]
Nice! 
WIP

**Comment by thgs** [comment]
Oh and I had started on that, was wondering how he would like to see the implementation.

**Comment by alexandermarston** [comment]
@thgs more than happy to see multiple examples of an implementation of this!

**Comment by thgs** [comment]
I was wondering if you want composer in the project actually. I am trying to do something lite without composer so far.

**Comment by alexandermarston** [comment]
@thgs I've not got a specific requirement to have something using Composer. If you can provide a good solution without it then definitely happy to take a look.

**Comment by alexandermarston** [comment]
As of 5a97b0c the code base has been refactored to take advantage of an object oriented style of code.

The project is now also using Smarty as a template engine.

Issue closed.
